### ISSUE TITLE
Multi-threading saturation

### ISSUE THREAD

**Issue by colepoirier** [rust-av/rav1e-by-gop#33]
Hi @shssoichiro,

I've been playing around with your multi-threaded implementation of rav1e, and it's really cool! One thing I've noticed is that the segmentation only takes place once, at the very beginning, and after this when individual segment encoding threads finish, those cores then sit idle. Is it possible to re-segment the scene of the slowest encoding thread, upon the finishing of the fastest encoding thread, so the more complex scene is then encoded n% faster due to the increased processing power from this work sharing? And to have this happen as each encoding thread finishes, so work is generally being processed by all available workers, instead of becoming seemingly increasingly inefficient and single-threaded as the encoding progresses? Essentially, it seems desirable to be able to utilize the full computational power of the cpu throughout the encoding process, but I don't have the understanding of the codebase or the necessary expertise to determine whether this is feasible or desirable.

**Comment by tleydxdy** [comment]
I'm trying to solve it by making the work distributed to each core as evenly as possible to begin with (mutiway number partitioning problem), that part I have finished. But I haven't yet figure out how to change the codebase so that you can encode a later segment before you encode previous ones. It should be possible.

**Comment by colepoirier** [comment]
Thanks for getting back to me so quickly @tleydxdy!! Very cool that you've already implemented the solution to the multi-way number partitioning problem. Out of curiosity, and because of my lack of familiarity with your codebase, would you mind telling me which sub-directories or files in the project are responsible for this coordination (?), if I'm even understanding the problem correctly...

**Comment by tleydxdy** [comment]
I'm still reading the code and trying to understand them now, but for mnp the idea is at https://git.uwaterloo.ca/y2497li/mnp-rs/blob/master/src/cga.rs 

also, I'm also just looking to contribute to this project :)

**Comment by shssoichiro** [comment]
> But I haven't yet figure out how to change the codebase so that you can encode a later segment before you encode previous ones.

That is the problem--currently, the expectation is that input is read from start to finish, and this is a hard requirement for piped input. We could theoretically read more segments ahead than we need to, but the issue with that is memory usage, and that's also why this tool uses so much memory already--holding the decoded video input uses a lot of memory.

I'm also not sure I understand the premise here. Currently, the only time this tool should not be using all available workers is near the end of an encode, when there are fewer remaining segments than workers. I don't think resegmenting makes sense--the segments are based on keyframes, so splitting past that would hurt compression.

**Comment by tleydxdy** [comment]
@shssoichiro the problem is the scheduling. it will happen near the end that some cores becomes idle while others still have (potentially lots of) work. If we could reshuffle the work around in a smart way rather than first come first serve so all cores finishes in the same time (or as close as possible) it is as if we could split the work anywhere we wanted.

right now the pipe method is already pretty hackish and has limited functionality. I don't see why this more complex scheduling can't be just for encoding of whole files.

the idea I could think of is to create a job queue in the first pass, split them optimally, and seek in the file with filesystem calls when we get to each jobs. 

or just create a bunch of input ivfs like we did for output if seeking is difficult.

**Comment by shssoichiro** [comment]
Seeking should be reasonably easy if we have a y4m input. On a side note, I agree that the pipe method is hackish, I'd love some way to simplify it without losing the existing functionality. (I don't know how common the use case I built the --fast-fp functionality for is, but I've found it to be quite useful since I'm often encoding with slow vapoursynth filtering.)

**Comment by lu-zero** [comment]
I came up with https://github.com/rust-av/rav1e-by-gop/pull/112, mixed with adding tiles it would fill nicely at least some of the idle time.
